### ISSUE TITLE
6.0.0-rc.2 ClassNotFoundException: jakarta.inject.Singleton

### ISSUE THREAD

**Issue by kpa23** [gitlab4j/gitlab4j-api#1001]
Trying spring boot 3.
I have error on "CentOS Linux 7 (Core)". 
Works fine(no errors) on both windows and Docker openjdk:17-jdk-alpine.

> 2023-07-16 00:42:37 [http-nio-8080-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.NoClassDefFoundError: jakarta/inject/Singleton] with root cause
java.lang.ClassNotFoundException: jakarta.inject.Singleton
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.glassfish.jersey.model.ContractProvider$Builder.<clinit>(ContractProvider.java:67)
	at org.glassfish.jersey.model.ContractProvider.builder(ContractProvider.java:49)
	at org.glassfish.jersey.model.internal.ComponentBag.modelFor(ComponentBag.java:522)
	at org.glassfish.jersey.model.internal.ComponentBag.lambda$registerModel$10(ComponentBag.java:454)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.model.internal.ComponentBag.registerModel(ComponentBag.java:446)
	at org.glassfish.jersey.model.internal.ComponentBag.register(ComponentBag.java:283)
	at org.glassfish.jersey.model.internal.CommonConfig.register(CommonConfig.java:417)
	at org.glassfish.jersey.client.ClientConfig$State.register(ClientConfig.java:216)
	at org.glassfish.jersey.client.ClientConfig.register(ClientConfig.java:612)
	at org.gitlab4j.api.GitLabApiClient.<init>(GitLabApiClient.java:247)
	at org.gitlab4j.api.GitLabApi.<init>(GitLabApi.java:444)
	at org.gitlab4j.api.GitLabApi.<init>(GitLabApi.java:391)
	at org.gitlab4j.api.GitLabApi.<init>(GitLabApi.java:330)
	at org.gitlab4j.api.GitLabApi.<init>(GitLabApi.java:121)
	at com.tander.egais.jirabrancher.service.git.GitServiceAbstract.getGit(GitServiceAbstract.java:30)

**Comment by kpa23** [comment]
Found workaround:
added dependency in pom:
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
            <version>3.1.0</version>
        </dependency>
and it fixed the bug. But I think there's a problem to solve inside the lib.
