### ISSUE TITLE
javax.ws.rs.core.MultivaluedMap.addAll(Ljava/lang/Object;[Ljava/lang/Object;)V

### ISSUE THREAD

**Issue by VioletCoding** [gitlab4j/gitlab4j-api#1041]
Stack trace:
```
Exception in thread "main" java.lang.NoSuchMethodError: javax.ws.rs.core.MultivaluedMap.addAll(Ljava/lang/Object;[Ljava/lang/Object;)V
	at org.glassfish.jersey.client.ClientRequest.accept(ClientRequest.java:323)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.accept(JerseyInvocation.java:224)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.accept(JerseyInvocation.java:147)
	at org.gitlab4j.api.GitLabApiClient.invocation(GitLabApiClient.java:841)
	at org.gitlab4j.api.GitLabApiClient.invocation(GitLabApiClient.java:801)
	at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:416)
	at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:404)
	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:214)
	at org.gitlab4j.api.ProjectApi.getProject(ProjectApi.java:748)
	at org.gitlab4j.api.ProjectApi.getProject(ProjectApi.java:680)
	at com.springkingon.cicd.util.GitLab.main(GitLab.java:51)
```

Code
```java
public static void main(String[] args) throws GitLabApiException {
    GitLabApi gitLabApi = new GitLabApi("http://172.10.0.201:82", "the token");
    Project project = gitLabApi.getProjectApi().getProject("/aaa%2Fbbb");
    System.out.println(project.toString());
}
```

pom.xml
```xml
<dependency>
    <groupId>org.gitlab4j</groupId>
    <artifactId>gitlab4j-api</artifactId>
    <version>5.3.0</version>
</dependency>
```

org.glassfish.jersey.client.ClientRequest

![image](https://github.com/gitlab4j/gitlab4j-api/assets/37135917/070ada48-78a7-418f-bac5-6cd98ba92f48)

environment：
Java 8
jakarta.ws.rs-api 2.1.6

I have searched for some issues, such as #158 , but it did not work.

**Comment by VioletCoding** [comment]
I have solved, and I found that Nacos also has a jersey-client, which conflicts with the jersey-client in gitlab-api. Just remove it to resolve the conflict.
```xml
<dependency>
        <groupId>com.alibaba.cloud</groupId>
        <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        <exclusions>
            <exclusion>
                <groupId>com.sun.jersey</groupId>
                <artifactId>jersey-client</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
```
