### ISSUE TITLE
Connection timed out: connect

### ISSUE THREAD

**Issue by Mr-ZhangJie** [gitlab4j/gitlab4j-api#353]
https://github.com/gitlab4j/gitlab4j-api/issues/185

I have the same problem as this person, but my url is accessible

org.gitlab4j.api.GitLabApiException: java.net.ConnectException: Connection timed out: connect
        at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:593)
        at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:193)
        at org.gitlab4j.api.Pager.<init>(Pager.java:85)
        at org.gitlab4j.api.RepositoryApi.getBranches(RepositoryApi.java:77)
        at org.gitlab4j.api.RepositoryApi.getBranches(RepositoryApi.java:44)
        at org.daac.version.controller.RepoController.findCloudBranchAll(RepoController.java:400)
        at sun.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:870)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:776)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:870)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.daac.CrosLoginFilter.doFilter(CrosLoginFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.daac.CrosLoginFilter.doFilter(CrosLoginFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:115)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:59)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:90)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection timed out: connect
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:284)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:753)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:752)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:419)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:319)
        at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:383)
        at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:371)
        at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:191)
        ... 71 more
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:390)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:282)
        ... 83 more

**Comment by gmessner** [comment]
@Mr-ZhangJie 
These connection issues have always proven to be caused by something outside of this library, so a stack trace really does not provide much helpful info.   Few questions:

1) Approximately how long does it take for the connection timeout to occur? 
2) How are you verifying that the server is accessible and are you certain that the same URL is used?  Sometimes there is a configuration issue in the apps that are using this library.
3) When you are checking that the server is accessible, are you checking from the same machine that the connection timeout occurs on?

**Comment by Mr-ZhangJie** [comment]
I have tried all the above points. This problem does not appear on other computers, and there should be no gitlab configuration timeout problem on this computer.
I typed gitlab's url address into the computer and it was accessible
I wonder if it's a network problem because this is a network inside Siemens

**Comment by Mr-ZhangJie** [comment]
But I deployed HTTPS on aliyun

**Comment by gmessner** [comment]
@Mr-ZhangJie 
I know you've closed this issue, but I was not clear whether you resolved it or not.  If you are still having an issue on the one inside the Siemens network, you may want to disable certificate verification, this takes care of the problem when the server is using a self-signed certificate.

You can disable certificate verification by simply calling the following on the ```GitLabApi``` instance:
```
gitLabApi.setIgnoreCertificateErrors(true);
```
Hope this helps.

**Comment by Mr-ZhangJie** [comment]
> @ Mr-ZhangJie
> 我知道你已经关闭了这个问题，但我不清楚你是否解决了这个问题。如果您在西门子网络内部仍然存在问题，则可能需要禁用证书验证，这可以在服务器使用自签名证书时解决问题。
> 
> 您只需在`GitLabApi`实例上调用以下内容即可禁用证书验证：
> 
> ```
> gitLabApi.setIgnoreCertificateErrors(true);
> ```
> 
> 希望这可以帮助。

谢谢你的解答 可能不是程序的问题这个可能需要找网络工程师进行协助
应为在外网任何情况下都可以使用,但是在内部局域网就出现这个异常


> @Mr-ZhangJie
> I know you've closed this issue, but I was not clear whether you resolved it or not. If you are still having an issue on the one inside the Siemens network, you may want to disable certificate verification, this takes care of the problem when the server is using a self-signed certificate.
> 
> You can disable certificate verification by simply calling the following on the `GitLabApi` instance:
> 
> ```
> gitLabApi.setIgnoreCertificateErrors(true);
> ```
> 
> Hope this helps.

Thank you for your answer, which may not be a problem of the program. This may require the assistance of the network engineer
This can be used in any situation on the external network, but this exception occurs on the internal LAN

**Comment by Mr-ZhangJie** [comment]
> @Mr-ZhangJie
> I know you've closed this issue, but I was not clear whether you resolved it or not. If you are still having an issue on the one inside the Siemens network, you may want to disable certificate verification, this takes care of the problem when the server is using a self-signed certificate.
> 
> You can disable certificate verification by simply calling the following on the `GitLabApi` instance:
> 
> ```
> gitLabApi.setIgnoreCertificateErrors(true);
> ```
> 
> Hope this helps.

Thank you for your answer, which may not be a problem of the program. This may require the assistance of the network engineer
This can be used in any situation on the external network, but this exception occurs on the internal LAN

**Comment by gmessner** [comment]
@Mr-ZhangJie 
Actually, the ```gitLabApi.setIgnoreCertificateErrors(true);``` is intended for internal networks, where self-signed certificates are very common, self signed certificates are rarely used on publically accessible networks.
