### ISSUE TITLE
Regression on JSON issues in 4.11.11? "Cannot deserialize instance of java.util.ArrayList out of START_OBJECT token"

### ISSUE THREAD

**Issue by hamishcunningham** [gitlab4j/gitlab4j-api#396]
hi, I seem to have a similar problem to #331 on 4.11.11 triggered with this code:

      GitLabApi gitLabApi = new GitLabApi(
        GitLabApi.ApiVersion.OAUTH2_CLIENT, 
        "https://gitlab.com",
        "my access token"
      );
      List<Project> projects = gitLabApi.getProjectApi().getProjects();

I get:

  Exception in thread "main" org.gitlab4j.api.GitLabApiException: Cannot deserialize instance of 
  `java.util.ArrayList` out of START_OBJECT token
  at [Source: (org.glassfish.jersey.client.internal.HttpUrlConnector$2); line: 1, column: 1]
        at org.gitlab4j.api.Pager.<init>(Pager.java:93)
        at org.gitlab4j.api.ProjectApi.getProjects(ProjectApi.java:106)
        at org.gitlab4j.api.ProjectApi.getProjects(ProjectApi.java:78)
        at org.gitlab4j.api.ProjectApi$getProjects.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at marking.GitRepo.connect(App.groovy:154)
        at marking.GitRepo$connect$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)

Any ideas? Tnx!

_Originally posted by @hamishcunningham in https://github.com/gitlab4j/gitlab4j-api/issues/331#issuecomment-507584299_

**Comment by gmessner** [comment]
@hamishcunningham 
This is unrelated to #331, that was an issue only related to Webhook event classes. 

The problem here is caused by the use of ```GitLabApi.ApiVersion.OAUTH2_CLIENT``` when creating the ```GitLabApi``` instance.  You should only use ```GitLabApi.ApiVersion.V3```, or ```GitLabApi.ApiVersion.V4```.

I will add some documentation in the Javadocs for ```ApiVersion```  that indicates ```GitLabApi.ApiVersion.OAUTH2_CLIENT```  is for internal use only.  I will also look into removing the ```GitLabApi.ApiVersion.OAUTH2_CLIENT``` value as it could be a bit confusing.

If you wish to login using OAUTH2 you should use one of the ```GitLabApi.oauth2Login()``` methods.

**Comment by hamishcunningham** [comment]
Thanks for the quick reply! I've got it working on V4 now. (I tried that earlier but it seemed to hang -- which I guess was me trying to pull down a complete list of all projects on gitlab.com! Oops!) 

Great library, thanks for your help.

**Comment by gmessner** [comment]
@hamishcunningham 
I have made modifications to ```GroupApi.getGroups()``` , ```ProjectApi.getProjects()``` , and ```UserApi.getUsers()```  to include a warning in the Javadocs about using these with https://gitlab.com.

I have also added a log output that logs the same warning when you use these methods against https://gitlab.com
