### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.gitlab4j.api.models.HealthCheckItem out of START_ARRAY token

### ISSUE THREAD

**Issue by aadrii** [gitlab4j/gitlab4j-api#468]
Hi,
I'm trying to use the health check API, but got an exception. It seems that the jsonn mapping for HealthCheckInfo object is bad.
Here is the stacktrace : 
```
javax.ws.rs.ProcessingException: Error reading entity from input stream.
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:889)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:321)
	at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:115)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:389)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:264)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:112)
....
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.gitlab4j.api.models.HealthCheckItem out of START_ARRAY token
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@455ab242; line: 1, column: 27] (through reference chain: org.gitlab4j.api.models.HealthCheckInfo["db_check"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1374)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:174)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1580)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:961)
	at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:838)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:257)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:236)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1091)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	... 50 more
```

I'm developping an application using javalin, with Kotlin 1.3 targetting jvm 1.8.
I was using `4.12.11` and updated to `4.12.17` but the error is still here.
I use gitlab-ce running with docker-compose. The image used is [12.4.2-ce.0](https://hub.docker.com/layers/gitlab/gitlab-ce/12.4.2-ce.0/images/sha256-88f1bcc39aa9917ac4b19022af441b64265d50e1f0c0fa2616d29a2cb82fb41a)
```
"RepoDigests": [
            "gitlab/gitlab-ce@sha256:88f1bcc39aa9917ac4b19022af441b64265d50e1f0c0fa2616d29a2cb82fb41a"
        ],
```

I can curl it successfully, and response is 
```json
{"status":"ok","db_check":[{"status":"ok"}],"redis_check":[{"status":"ok"}],"cache_check":[{"status":"ok"}],"queues_check":[{"status":"ok"}],"shared_state_check":[{"status":"ok"}],"gitaly_check":[{"status":"ok","labels":{"shard":"default"}}]}
```

Seems ok with `gitlab/gitlab-ce:12.3.6-ce.0`, curl response is 
```
{
  "db_check": {
    "status": "ok"
  },
  "redis_check": {
    "status": "ok"
  },
  "cache_check": {
    "status": "ok"
  },
  "queues_check": {
    "status": "ok"
  },
  "shared_state_check": {
    "status": "ok"
  },
  "gitaly_check": {
    "status": "ok",
    "labels": {
      "shard": "default"
    }
  }
}
```

**Comment by gmessner** [comment]
@aadrii 
Your error is because GitLab changed the format of the message in 12.4, see:
https://docs.gitlab.com/ee/user/admin_area/monitoring/health_check.html#liveness

GitLab does this sort of thing all the time, it is sometimes difficult to keep up with the changes.  I will see what I can do about making it compatible with all versions.  I will let you know when I have an update.

**Comment by gmessner** [comment]
@aadrii 
I have added the handling of the new health check format that was introduced with 12.4.  
Release 4.12.18 is now available.  When you have time please verify and close this issue.

**Comment by aadrii** [comment]
@gmessner 
Thanks for the quick reply and the quick fix.
Tested with gitlab-ce=12.4.2-ce.0, works fine.
Still work fine with gitlab-ce=12.3.6-ce.0 too.
