### ISSUE TITLE
NullPointerException at org.glassfish.hk2.utilities.ServiceLocatorUtilities.addClasses

### ISSUE THREAD

**Issue by tomasbjerre** [gitlab4j/gitlab4j-api#523]
I got an issue reported in my tool using this library: https://github.com/jenkinsci/violation-comments-to-gitlab-plugin/issues/26

The stacktrace shows an NPE in `org.glassfish.hk2.utilities.ServiceLocatorUtilities` but perhaps you recognize the issue?

```
java.lang.RuntimeException: Could not get project 1249
at se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.(GitLabCommentsProvider.java:72)
at se.bjurr.violations.comments.gitlab.lib.ViolationCommentsToGitLabApi.toPullRequest(ViolationCommentsToGitLabApi.java:175)
at org.jenkinsci.plugins.jvctgl.perform.JvctglPerformer.doPerform(JvctglPerformer.java:160)
at org.jenkinsci.plugins.jvctgl.perform.JvctglPerformer$2.invoke(JvctglPerformer.java:268)
at org.jenkinsci.plugins.jvctgl.perform.JvctglPerformer$2.invoke(JvctglPerformer.java:256)
at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3069)
at hudson.remoting.UserRequest.perform(UserRequest.java:211)
at hudson.remoting.UserRequest.perform(UserRequest.java:54)
at hudson.remoting.Request$2.run(Request.java:369)
at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: org.gitlab4j.api.GitLabApiException
at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:604)
at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:182)
at org.gitlab4j.api.ProjectApi.getProject(ProjectApi.java:665)
at se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.(GitLabCommentsProvider.java:70)
... 13 more

Caused by: java.lang.NullPointerException
at org.glassfish.hk2.utilities.ServiceLocatorUtilities.addClasses(ServiceLocatorUtilities.java:411)
at org.glassfish.hk2.utilities.ServiceLocatorUtilities.enablePerThreadScope(ServiceLocatorUtilities.java:83)
at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.createLocator(AbstractHk2InjectionManager.java:92)
at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.(AbstractHk2InjectionManager.java:62)
at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.(ImmediateHk2InjectionManager.java:38)
at org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory$Hk2InjectionManagerStrategy$1.createInjectionManager(Hk2InjectionManagerFactory.java:55)
at org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory.create(Hk2InjectionManagerFactory.java:73)
at org.glassfish.jersey.internal.inject.InjectionManagerFactory.create(InjectionManagerFactory.java:32)
at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:44)
at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:408)
at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:802)
at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:261)
at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:119)
at org.glassfish.jersey.client.JerseyInvocation.(JerseyInvocation.java:88)
at org.glassfish.jersey.client.JerseyInvocation.(JerseyInvocation.java:84)
at org.glassfish.jersey.client.JerseyInvocation.(JerseyInvocation.java:75)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:395)
at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:295)
at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:384)
at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:372)
at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:180)
... 15 more
```

**Comment by gmessner** [comment]
@tomasbjerre Unfortunately, I cannot determine much from the stack trace.  I would imagine that this plugin is working but this one user has a setup (other plugins) that might be causing a dependency version problem with Jersey.

**Comment by tomasbjerre** [comment]
Ok, thanks for taking a look!
