### ISSUE TITLE
Error " java.lang.NoSuchMethodError" on Websphere Liberty

### ISSUE THREAD

**Issue by kk12345-png** [gitlab4j/gitlab4j-api#555]
We tried to use gitlab4j API from an application deployed on Websphere liberty . We got the error as below:

[ 2020-04-17 11:37:31,739 ] --- [ 9446 ] --- [ INFO ] --- [ com.ibm.almEnhancement.BL.GitClmMembers ] --- [ 607 ] --- [ testGit ] ---[ Reaching inside fetchGitlabGroupUsers........... ]
[ 2020-04-17 11:37:31,740 ] --- [ 9446 ] --- [ INFO ] --- [ com.ibm.almEnhancement.BL.GitClmMembers ] --- [ 615 ] --- [ testGit ] ---[ Trying to authenticate with gitlab........ ]
[ 2020-04-17 11:37:31,890 ] --- [ 9446 ] --- [ DEBUG ] --- [ org.springframework.web.servlet.FrameworkServlet ] --- [ 1101 ] --- [ logResult ] ---[ Failed to complete request: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: javax/ws/rs/core/MultivaluedMap.addAll(Ljava/lang/Object;[Ljava/lang/Object;)V (loaded from file:/IBM/JazzTeamServer606/server/liberty/wlp/lib/../dev/api/spec/com.ibm.websphere.javaee.jaxrs.1.1_1.0.20.jar by org.eclipse.osgi.internal.loader.EquinoxClassLoader@8299ff34[com.ibm.websphere.javaee.jaxrs.1.1:1.0.20.cl180120180309-2209(id=478)]) called from class org.glassfish.jersey.client.ClientRequest (loaded from file:/IBM/JazzTeamServer/server/liberty/wlp/usr/servers/almautomation/apps/expanded/almAdministration.war/WEB-INF/lib/jersey-client-2.29.1.jar by com.ibm.ws.classloading.internal.AppClassLoader@404b4aa4). ]
[ERROR   ] SRVE0777E: Exception thrown by application class 'org.springframework.web.servlet.DispatcherServlet.doDispatch:1,055'
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: javax/ws/rs/core/MultivaluedMap.addAll(Ljava/lang/Object;[Ljava/lang/Object;)V (loaded from file:/IBM/JazzTeamServer606/server/liberty/wlp/lib/../dev/api/spec/com.ibm.websphere.javaee.jaxrs.1.1_1.0.20.jar by org.eclipse.osgi.internal.loader.EquinoxClassLoader@8299ff34[com.ibm.websphere.javaee.jaxrs.1.1:1.0.20.cl180120180309-2209(id=478)]) called from class org.glassfish.jersey.client.ClientRequest (loaded from file:/IBM/JazzTeamServer/server/liberty/wlp/usr/servers/almautomation/apps/expanded/almAdministration.war/WEB-INF/lib/jersey-client-2.29.1.jar by com.ibm.ws.classloading.internal.AppClassLoader@404b4aa4).
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at [internal classes]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at [internal classes]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at com.ibm.almEnhancement.Utils.JWTAuthorizationFilter.doFilterInternal(JWTAuthorizationFilter.java:45)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at [internal classes]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at [internal classes]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at [internal classes]
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

**Comment by gmessner** [comment]
@kk12345-png 
This is because your dependencies are likely using an older version of JAX-RS.  What version of JAX-RS is listed in your dependencies?

**Comment by kk12345-png** [comment]
@gmessner  Thanks for replying . JAX-RS version is 2.1 . Below pasted extract from pom.xml. Could you please advise

<dependency>
			<groupId>javax.ws.rs</groupId>
			<artifactId>javax.ws.rs-api</artifactId>
			<version>2.1</version>
		</dependency>

**Comment by gmessner** [comment]
@kk12345-png ```javax.ws.rs-api``` has been retired and replaced with ```jakarta.ws.rs-api``` version 2.1.6.

See: https://javalibs.com/artifact/javax.ws.rs/javax.ws.rs-api

**Comment by kk12345-png** [comment]
@gmessner  we replaced it with jakarta.ws.rs-api , but we are still getting same error

[12:21 PM] Sudhambarish V
    Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: javax/ws/rs/core/MultivaluedMap.addAll(Ljava/lang/Object;[Ljava/lang/Object;)V (loaded from file:/C:/CLM_606/IBM/JazzTeamServer/server/liberty/wlp/lib/../dev/api/spec/com.ibm.websphere.javaee.jaxrs.1.1_1.0.20.jar by org.eclipse.osgi.internal.loader.EquinoxClassLoader@e3977178[com.ibm.websphere.javaee.jaxrs.1.1:1.0.20.cl180120180309-2209(id=272)]) called from class org.glassfish.jersey.client.ClientRequest (loaded from file:/C:/CLM_606/IBM/JazzTeamServer/server/liberty/wlp/usr/servers/almautomation/apps/expanded/almAdministration.war/WEB-INF/lib/jersey-client-2.29.1.jar by com.ibm.ws.classloading.internal.AppClassLoader@b6e9f6d3). ]

**Comment by gmessner** [comment]
@kk12345-png My apologies as I cannot really provide much help on this you have a dependency issue that must be corrected.This is not an issue with GitLab4J-API.

From the exception I can see that the ```javax.ws.rs.api``` stuff is not being pulled from  ```jakarta.ws.rs-api``` it is being pulled from ```websphere.javaee.jaxrs.1.1_1.0.20.jar``` which is a very old version of JAX-RS 1.0,  this library requires JAX-RS 2+

**Comment by gmessner** [comment]
@kk12345-png I am closing this issue, if you still require help please feel free to re-open it.
