### ISSUE TITLE
Problem encountered while trying to use GitLabApi.oauth2Login().

### ISSUE THREAD

**Issue by SamerShboul** [gitlab4j/gitlab4j-api#568]
Hi @gmessner, hope you are doing well.

I'm trying to use your awesome API in order to access a public repository (https://gitlab.com/crossref/open_funder_registry), and see the releases, etc...
This is a snippet of what I used until now:
`        GitLabApi gitLabApi = GitLabApi.oauth2Login("https://gitlab.com/sshboul", "username", "password");
`
But an HTML output keep showing while that, with something, contains: "The page could not be found or you don't have permission to view it"

So, I'm really confused, how to get rid of this issue, and I'm wondering if I can use another way of doing it?
Another thing, is there an ability to access let's say a public repo like what I mentioned above, without any personal authentication details? bcz I will use this API in company stuff, and it will be something not preferable to do if I use some personal stuff.

Thanks!

**Comment by gmessner** [comment]
@SamerShbou
The URL you are using is not correct, it should just be "https://gitlab.com"

Additionally, the Personal Access Token is the preferred mechanism for authenticating with the GitLab API.  Go to this link for info on creating a Personal Access Token:
https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html

Once you have created a personal access token you would create a GitLabApi instance as follows:
```
GitLabApi gitLabApi = new GitLabApi("http://gitlab.com", "YOUR_PERSONAL_ACCESS_TOKEN");
```

**Comment by SamerShboul** [comment]
@gmessner,

Mmm, actually I've also tried that, and in that turn my code was:
`GitLabApi gitLabApi = new GitLabApi("https://gitlab.com", "MY_ACCESS_TOKEN");
        List<Release> releases = gitLabApi.getReleasesApi().getReleases(14100417);
        System.out.println(releases.get(0).getName());`

But, with no luck unfortunately, this is the error was occurring:
`Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:405)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:444)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:182)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:682)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:482)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4178)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3997)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3072)
	at org.gitlab4j.api.Pager.<init>(Pager.java:95)
	at org.gitlab4j.api.ReleasesApi.getReleases(ReleasesApi.java:47)
	at org.gitlab4j.api.ReleasesApi.getReleases(ReleasesApi.java:33)
	at com.atypon.externaltaxonomies.GitLabTest.main(GitLabTest.java:31)` 

And the same error appeared when tried to use the ReleaseApi with the same ProjectId.
So, I'm wondering here, am I using the Tags/RelasesApi in the correct way with regards to determining the project? or I missed something here?

**Comment by SamerShboul** [comment]
This exception was been shown bcz of dependencies-missed.
I've just added:
`<dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.11.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.11.0</version>
        </dependency>`
and everything ran as expected.

Thanks, @gmessner for your help.
closing...

**Comment by gmessner** [comment]
@SamerShboul Good work on figuring this out.

**Comment by lsysharon** [comment]
Hi, I've encountered similar problem.
It seems invalid to use Project Access Token for authenticating with the GitLab API, right?

**Comment by lsysharon** [comment]
It doesn't work as follows.
GitLabApi gitLabApi = new GitLabApi("https://gitlab.com", "PROJECT ACCESS_TOKEN NOT PERSONAL");

and no information from
https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html#scopes-for-a-project-access-token
