### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by dkumarapandian** [gitlab4j/gitlab4j-api#571]
Hi 
I am using below version of gitlab4j-api. I am able to login and get some details from the GIT Server. But we try to list the groups, projects or user I am getting connection refused error. I am using a private token with admin rights for the GITLabs.

<dependency>
	<groupId>org.gitlab4j</groupId>
	<artifactId>gitlab4j-api</artifactId>
	<version>4.14.28</version>
</dependency>

Below is the output and exception I am having.

Thu May 07 18:43:09 IST 2020 - TestGitAccess main gitLabApi.getApiVersion() : 'V4'
Thu May 07 18:43:09 IST 2020 - TestGitAccess main gitLabApi.getDefaultPerPage() : '96'
Thu May 07 18:43:09 IST 2020 - TestGitAccess main gitLabApi.getGroupApi() : 'org.gitlab4j.api.GroupApi@75bd9247'
Thu May 07 18:43:09 IST 2020 - TestGitAccess main gitLabApi.getProjectApi() : 'org.gitlab4j.api.ProjectApi@3f3afe78'
Thu May 07 18:43:09 IST 2020 - TestGitAccess main gitLabApi.getUserApi() : 'org.gitlab4j.api.UserApi@4411d970'
org.gitlab4j.api.GitLabApiException: java.net.ConnectException: Connection refused: connect
	at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:655)
	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:215)
	at org.gitlab4j.api.Pager.<init>(Pager.java:92)
	at org.gitlab4j.api.UserApi.getActiveUsers(UserApi.java:155)
	at org.gitlab4j.api.UserApi.getActiveUsers(UserApi.java:122)
	at gitaccess.TestGitAccess.main(TestGitAccess.java:29)
Caused by: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused: connect
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:261)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:296)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:609)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:608)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:395)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:295)
	at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:412)
	at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:400)
	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:213)
	... 4 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:367)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:259)
	... 16 more
[code.txt](https://github.com/gitlab4j/gitlab4j-api/files/4593154/code.txt)

**Comment by gmessner** [comment]
@dkumarapandian This is almost always because the URL is incorrect.  Or it is a network configuration issue, it is not something wrong with this library.

I would suggest using Postman or Curl and see if you can gain access to the GitLab API that way, it might help you figure out what you are doing wrong.

**Comment by dkumarapandian** [comment]
gmessner

Just want to understand, if the URL is not correct how can I get GroupAPI, ProjectAPI and UserAPI?

Or these object will connect to GIT while invoking other methods with in it (like getActiveUsers() method)?

**Comment by gmessner** [comment]
Yes, ```GroupApi```, ```ProjectApi```, and ```UserApi``` are just singleton instances, they do no communication with anything unless you call a method on them like ```getActiveUsers()```

**Comment by dkumarapandian** [comment]
Thanks gmessner.

I was able to connect to the GIT through API. In browser we are using https for the GIT URL. So I have tried with the same URL. When I changed to http we are able to connect from the Java application.
