### ISSUE TITLE
Question/Advice on optimizing long data fetching process

### ISSUE THREAD

**Issue by marcojahn** [gitlab4j/gitlab4j-api#586]
I am using GitLab (as other systems) to fetch data for some analytics (long story very short) and save these documents to an elastic.

One of my import processes took >2h to complete which does the following
* loop repos of a group (~1800), for each repo it does
** fetches project data (statistics,...)
** members (direct, inherited)
** processes used languages
** calculates some date/time values (last activity, last commit, ...)

Each document takes ~4-6s until we got all data (with 6-7 requests to GitLab)

To speed up this process I implemented threading as follows (simplified):

```java
Executors.newFixedThreadPool(2);

// created outside and passed
this.gitLabApiProjectApi = gitLabApi.getProjectApi();

Pager<Project> pagerProjects = this.gitLabApiProjectApi.getProjects(projectFilter, LIMIT_ITEMS_PER_PAGE);

while (pagerProjects.hasNext()) {
    for (Project project : pagerProjects.next()) {

        // processing each elastic document
        Runnable runnable = () -> {
            // make more GitLab API requets, create a document send to elastic
            new SpecificElasticDocument(this.gitLabApiProjectApi);
            saveToElastic();
        }
        executor.execute(runnable);
        
// some code to finish stuff


// this is done inside new SpecificElasticDocument constructor, computation happens inside the object itself
this.gitLabProject = gitLapProjectApi.getProject(projectId, true);
this.getGitLabProjectDirectMembers = gitLapProjectApi.getMembers(projectId);
this.gitLabProjectInheritedMembers = gitLapProjectApi.getAllMembers(projectId);
this.gitLabProjectLanguages = gitLapProjectApi.getProjectLanguages(projectId);
```

The threading itself is working, the process now takes about 1h15m to finish.

My problem at the moment is, that I am not able to use more threads than `2`, otherwise the process will fail with a `javax.net.ssl.SSLHandshakeException` (detailed stacktrace below).
My guess is, that there is a problem with to many (or to less available) http connections that are openen and/or should be created.
The exception is thrown at one of these four lines `gitLapProjectApi.get*`.

Do you have any advice on how I can speed up the process without building some kind of cache that reduces the calls done with your library ?
Is there a way to optimize the http connection handling or am I able to close open connections manually?

<details>
  <summary>Full stack trace</summary>

```
Exception in thread "pool-4-thread-19" java.lang.RuntimeException: org.gitlab4j.api.GitLabApiException: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at org.gitlab4j.api.Pager.page(Pager.java:338)
	at org.gitlab4j.api.Pager.next(Pager.java:241)
	at org.gitlab4j.api.Pager.all(Pager.java:357)
	at org.gitlab4j.api.ProjectApi.getAllMembers(ProjectApi.java:1372)
	at d.d.v.d.d.adapter.gitlab.domainmodel.ELKRepositories.<init>(ELKRepositories.java:99)
	at d.d.v.d.d.adapter.gitlab.RepositoriesService.createELKRepositoryDocumentDTO(RepositoriesService.java:185)
	at d.d.v.d.d.adapter.gitlab.RepositoriesService.lambda$createRepositories$0(RepositoriesService.java:148)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.gitlab4j.api.GitLabApiException: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:655)
	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:215)
	at org.gitlab4j.api.Pager.page(Pager.java:327)
	... 9 more
Caused by: javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:260)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:254)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:736)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:735)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:395)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:295)
	at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:412)
	at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:400)
	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:213)
	... 10 more
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1313)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1055)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:395)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:366)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:258)
	... 22 more
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
		at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:398)
		... 30 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1144)
	... 32 more
```

</details>

**Comment by gmessner** [comment]
@marcojahn Sorry about the delay in responding I'm recovering from major surgery and cannot spend much time at my computer.

My suggestion is to create a separate GitLabApi instance for working with ES and use an instance of ExecutorService setup to only run one at a time.

**Comment by gmessner** [comment]
@marcojahn Can we close this issue?

**Comment by marcojahn** [comment]
Sry, yes for sure
