### ISSUE TITLE
How to create project in group and subgroup?

### ISSUE THREAD

**Issue by stijnb1234** [gitlab4j/gitlab4j-api#610]
I want to create a project in a group and subgroup.

So my group is called d-group1, and my subgroups are websites and stijn.

So the path should be /d-group1/websites/stijn, but that's invalid.

The code I'm using:
```java
Project projectSpec = new Project()
    .withName("Test")
    .withPath("/d-group1/websites/stijn/")
    .withPublic(false);

Project project = Main.getGitLabApi().getProjectApi().createProject(projectSpec);
````

How to get this working?

![image](https://user-images.githubusercontent.com/27051051/91284729-976a8680-e78c-11ea-8087-03cc9057a239.png)

**Comment by gmessner** [comment]
The code should look as follows:
```
Project projectSpec = new Project()
    .withName("Test")
    .withPath("/d-group1/websites/stijn/test")
    .withPublic(false);

Project project = Main.getGitLabApi().getProjectApi().createProject(projectSpec);
```

**Comment by stijnb1234** [comment]
This returns an error.

```
org.gitlab4j.api.GitLabApiException: The following fields have validation errors: path
	at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:633)
	at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:286)
	at org.gitlab4j.api.ProjectApi.createProject(ProjectApi.java:1053)
	at org.gitlab4j.api.ProjectApi.createProject(ProjectApi.java:945)
	at me.SBDeveloper.DGHoofdBot.Commands.Bestellingen.Order.createRepo(Order.java:785)
	at me.SBDeveloper.DGHoofdBot.Main.main(Main.java:168)
```

**Comment by tonyyls** [comment]
i meet the same problem , help ...

**Comment by tonyyls** [comment]
we should use like this:

```
Project projectSpec = new Project()
                .withName("app_guid")
                .withNamespaceId(1775)   //groupId
                .withDescription("测试描述内容")
                .withPublic(false);
        Project newProject = gitLabServ.api.getProjectApi().createProject(projectSpec);
```
