### ISSUE TITLE
Issue with JDK-11

### ISSUE THREAD

**Issue by squalou** [gitlab4j/gitlab4j-api#618]
Hi,
I'm using a Jenkins plugin that in turns relies on this lib.
I'm trying to track if the issue I face comes from the plugin or the lib (I'm also discussing the issue on plugin side).

I'd like your point of view on what happens. Maybe by chance the stacktrace will mean something to you :)

When running with a jdk8, eveything is fine.

When I switch to opendk11.0.8 here s what I face 

```
java.lang.RuntimeException: Could not get project   aaa/bbbb
  	at se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.<init>(GitLabCommentsProvider.java:73)
  	at se.bjurr.violations.comments.gitlab.lib.ViolationCommentsToGitLabApi.toPullRequest(ViolationCommentsToGitLabApi.java:175)
  	at org.jenkinsci.plugins.jvctgl.perform.JvctglPerformer.doPerform(JvctglPerformer.java:167)
  	at org.jenkinsci.plugins.jvctgl.perform.JvctglPerformer$2.invoke(JvctglPerformer.java:275)
  	at org.jenkinsci.plugins.jvctgl.perform.JvctglPerformer$2.invoke(JvctglPerformer.java:263)
  	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3073)
  	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
  	at hudson.remoting.Request$2.run(Request.java:369)
  	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
  	at java.base/java.lang.Thread.run(Thread.java:834)
  Caused by: org.gitlab4j.api.GitLabApiException
  	at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:655)
  	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:215)
  	at org.gitlab4j.api.ProjectApi.getProject(ProjectApi.java:673)
  	at se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.<init>(GitLabCommentsProvider.java:71)
  	... 14 more
  Caused by: java.lang.NullPointerException
  	at org.glassfish.hk2.utilities.ServiceLocatorUtilities.addClasses(ServiceLocatorUtilities.java:411)
  	at org.glassfish.hk2.utilities.ServiceLocatorUtilities.enablePerThreadScope(ServiceLocatorUtilities.java:83)
  	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.createLocator(AbstractHk2InjectionManager.java:92)
  	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.<init>(AbstractHk2InjectionManager.java:62)
  	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.<init>(ImmediateHk2InjectionManager.java:38)
  	at org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory$Hk2InjectionManagerStrategy$1.createInjectionManager(Hk2InjectionManagerFactory.java:55)
  	at org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory.create(Hk2InjectionManagerFactory.java:73)
  	at org.glassfish.jersey.internal.inject.InjectionManagerFactory.create(InjectionManagerFactory.java:32)
  	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:44)
  	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:412)
  	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
  	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:807)
  	at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:219)
  	at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:610)
  	at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:364)
  	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:192)
  	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:36)
  	at org.gitlab4j.api.GitLabApiClient.invocation(GitLabApiClient.java:796)
  	at org.gitlab4j.api.GitLabApiClient.invocation(GitLabApiClient.java:761)
  	at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:412)
  	at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:400)
  	at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:213)
```

**Comment by squalou** [comment]
I managed to check further : it's really related to the plugin using the lib, not the lib
=> closing this
