### ISSUE TITLE
connect with gitlab.com APIs, throws invalid_client Exception  

### ISSUE THREAD

**Issue by thinking-cloud** [gitlab4j/gitlab4j-api#701]
I need to connect with gitlab.com APIs. I am running the following code:
`
public static void main(String[] args) throws GitLabApiException {
	GitLabApi gitLabApi = GitLabApi.oauth2Login("http://10.10.6.9:8880", "root", "Aa123456");
	System.out.println(gitLabApi);
}
`
I receive an Exception:
`
Exception in thread "main" org.gitlab4j.api.GitLabApiException: invalid_client
	at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:633)
	at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:323)
	at org.gitlab4j.api.GitLabApi.oauth2Login(GitLabApi.java:293)
	at org.gitlab4j.api.GitLabApi.oauth2Login(GitLabApi.java:140)
	at com.bocloud.devops.assets.code.adapter.Test.main(Test.java:18)
`
my use gitlab.com version： GitLab Community Edition 13.9.4

@gmessner Can you tell me what is wrong?  thanks！

**Comment by jabby** [comment]
Hello, your problem is probably coming from a breaking change in GitLab 13.9. See https://github.com/gitlab4j/gitlab4j-api/issues/679#issuecomment-814773657 for more explanation. As it is reverted in 13.10 I don't want to spend times on this. I suggest you if possible to upgrade to GitLab CE 13.10.
