### ISSUE TITLE
Create tag with release notes crashes server

### ISSUE THREAD

**Issue by BugsBunnyBR** [gitlab4j/gitlab4j-api#735]
When creating a new tag with a release note, I get

```
Caused by: org.gitlab4j.api.GitLabApiException: 500 Internal Server Error
	at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:633)
	at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:286)
	at org.gitlab4j.api.TagsApi.createTag(TagsApi.java:239)
```

I looked at the [implementation](https://github.com/gitlab4j/gitlab4j-api/blob/master/src/main/java/org/gitlab4j/api/TagsApi.java#L238) and the documentation for [tag creation](https://docs.gitlab.com/ee/api/tags.html#create-a-new-tag)

the parameter `release_description` is not shown in the documentation and whenever I give it a non empty value I get that exception.

Would you have a workaround for this?

**Comment by chrisrohr** [comment]
One work around is to use the release api instead of the tag api.  Specifically the Gitlab docs have the following information about tagging which would remove the need for 2 calls:

> If a tag specified in `tag_name` doesn’t exist, the release is created from `ref` and tagged with `tag_name`. It can be a commit SHA, another tag name, or a branch name.

Url for this api on Gitlab's docs is https://docs.gitlab.com/ee/api/releases/#create-a-release and looks like it has been included in this library since at least 4.14.9

**Comment by BugsBunnyBR** [comment]
Yeah, I am using the release method, but it took me a while to figure it out. So removing or at least deprecating that tag method seems like a good action from the library part.
