### ISSUE TITLE
Exception when running getApplicationSettingsApi().getApplicationSettings()

### ISSUE THREAD

**Issue by nightman68** [gitlab4j/gitlab4j-api#818]
I have a small application which is trying to get the application settings from a self hosted GitLab instance. Running the command like this:
``` java
Object settings = gitLabApiSource.getApplicationSettingsApi().getApplicationSettings().getSetting("group_import_limit");
```
throws an Eception:

<details><summary>stacktrace</summary>
&nbsp;

GitLab4j API version (source): V4

connecting to GitLab API on target server <https://gitlab.corp>...Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: abuse_notification_email, type: NullNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: admin_mode, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: asset_proxy_allowlist, type: ArrayNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: default_branch_name, type: NullNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: disable_feed_token, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: domain_denylist, type: ArrayNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: domain_denylist_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: domain_denylist_raw, type: TextNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: domain_allowlist, type: ArrayNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: domain_allowlist_raw, type: TextNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: outbound_local_requests_allowlist_raw, type: TextNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: external_pipeline_validation_service_timeout, type: NullNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: external_pipeline_validation_service_token, type: NullNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: external_pipeline_validation_service_url, type: NullNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: floc_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: gitpod_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: gitpod_url, type: TextNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: help_page_documentation_base_url, type: NullNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: in_product_marketing_emails_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: invisible_captcha_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: max_yaml_size_bytes, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: max_yaml_depth, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: notify_on_unknown_sign_in, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: personal_access_token_prefix, type: TextNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: kroki_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: kroki_url, type: NullNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: kroki_formats, type: ObjectNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: repository_storages_weighted, type: ObjectNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: require_admin_approval_after_user_signup, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: spam_check_api_key, type: NullNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_authenticated_git_lfs_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_authenticated_git_lfs_period_in_seconds, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_authenticated_git_lfs_requests_per_period, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_authenticated_packages_api_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_authenticated_packages_api_period_in_seconds, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_authenticated_packages_api_requests_per_period, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_authenticated_files_api_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_authenticated_files_api_period_in_seconds, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_authenticated_files_api_requests_per_period, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_authenticated_deprecated_api_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_authenticated_deprecated_api_period_in_seconds, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_authenticated_deprecated_api_requests_per_period, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_unauthenticated_api_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_unauthenticated_api_period_in_seconds, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_unauthenticated_api_requests_per_period, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_unauthenticated_packages_api_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_unauthenticated_packages_api_period_in_seconds, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_unauthenticated_packages_api_requests_per_period, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_unauthenticated_files_api_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_unauthenticated_files_api_period_in_seconds, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_unauthenticated_files_api_requests_per_period, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_unauthenticated_deprecated_api_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_unauthenticated_deprecated_api_period_in_seconds, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: throttle_unauthenticated_deprecated_api_requests_per_period, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: usage_ping_features_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: diff_max_files, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: diff_max_lines, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: mailgun_signing_key, type: NullNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: mailgun_events_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: notes_create_limit, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: notes_create_limit_allowlist_raw, type: TextNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: project_import_limit, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: project_export_limit, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: project_download_export_limit, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: group_import_limit, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: group_export_limit, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: group_download_export_limit, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: wiki_page_max_content_bytes, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: container_registry_delete_tags_service_timeout, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: rate_limiting_response_text, type: TextNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: container_registry_expiration_policies_worker_capacity, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: container_registry_cleanup_tags_service_max_list_size, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: container_registry_import_max_tags_count, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: container_registry_import_max_retries, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: container_registry_import_start_max_retries, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: container_registry_import_max_step_duration, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: container_registry_import_target_plan, type: TextNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: container_registry_import_created_before, type: TextNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: keep_latest_artifact, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: whats_new_variant, type: TextNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: user_deactivation_emails_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: sentry_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: sentry_dsn, type: NullNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: sentry_clientside_dsn, type: NullNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: sentry_environment, type: NullNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: sidekiq_job_limiter_mode, type: TextNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: sidekiq_job_limiter_compression_threshold_bytes, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: sidekiq_job_limiter_limit_bytes, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: suggest_pipeline_enabled, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: user_email_lookup_limit, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: deactivate_dormant_users, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: automatic_purchased_storage_allocation, type: BooleanNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: elasticsearch_client_request_timeout, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: elasticsearch_indexed_field_length_limit, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: elasticsearch_indexed_file_size_limit_kb, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: elasticsearch_max_bulk_concurrency, type: IntNode
Mar 10, 2022 10:54:06 AM org.gitlab4j.api.ApplicationSettingsApi parseApplicationSettings
WARNING: Unknown setting: elasticsearch_max_bulk_size_mb, type: IntNode
</details>

``` java
java.lang.NullPointerException
	at org.gitlab4j.api.models.Setting.validate(Setting.java:1202)
	at org.gitlab4j.api.models.ApplicationSettings.addSetting(ApplicationSettings.java:97)
	at org.gitlab4j.api.ApplicationSettingsApi.parseApplicationSettings(ApplicationSettingsApi.java:145)
	at org.gitlab4j.api.ApplicationSettingsApi.getApplicationSettings(ApplicationSettingsApi.java:36)
        ...
Application terminated.
``` 
gitlab4j-api: 4.19.0
GitLab: 14.7.4

Thanks!

**Comment by nightman68** [comment]
I tested the behavior again:
``` java
WARNING: Unknown setting: elasticsearch_max_bulk_size_mb, type: IntNode
org.gitlab4j.api.GitLabApiException: 'elasticsearch_namespace_ids' value is of incorrect type, is String[], should be Integer[]
	at org.gitlab4j.api.models.Setting.validate(Setting.java:1214)
	at org.gitlab4j.api.models.ApplicationSettings.addSetting(ApplicationSettings.java:97)
	at org.gitlab4j.api.ApplicationSettingsApi.parseApplicationSettings(ApplicationSettingsApi.java:145)
	at org.gitlab4j.api.ApplicationSettingsApi.getApplicationSettings(ApplicationSettingsApi.java:36)
	at nightwork.git.util.Migrate.run(Migrate.java:89)
	at nightwork.git.util.Migrate.main(Migrate.java:559)
```

gitlab4j-api: 5.0.1
GitLab: 14.7.4

**Comment by ptrts** [comment]
Also, every invocation of ```ApplicationSettingsApi#updateApplicationSetting(String, Object)``` results in the following

<pre>
Caused by: org.gitlab4j.api.GitLabApiException: 'elasticsearch_namespace_ids' value is of incorrect type, is String[], should be Integer[]
	at org.gitlab4j.api.models.Setting.validate(Setting.java:1214) ~[gitlab4j-api-5.0.1.jar:na]
	at org.gitlab4j.api.models.ApplicationSettings.addSetting(ApplicationSettings.java:97) ~[gitlab4j-api-5.0.1.jar:na]
	at org.gitlab4j.api.ApplicationSettingsApi.parseApplicationSettings(ApplicationSettingsApi.java:145) ~[gitlab4j-api-5.0.1.jar:na]
	at org.gitlab4j.api.ApplicationSettingsApi.updateApplicationSetting(ApplicationSettingsApi.java:100) ~[gitlab4j-api-5.0.1.jar:na]
	at org.gitlab4j.api.ApplicationSettingsApi.updateApplicationSetting(ApplicationSettingsApi.java:78) ~[gitlab4j-api-5.0.1.jar:na]
	at app.main.dynamic.wiring.GitlabHookRegistrator.lambda$start$0(GitlabHookRegistrator.java:55) ~[main/:na]
	... 22 common frames omitted
</pre>

**Comment by nightman68** [comment]
I tested the behavior again with gitlab4j-api: 5.3.0 and GitLab 15.11.8 with the same error.

**Comment by nightman68** [comment]
I tested it again with gitlab4j-api 5.8.0 and GitLab 17.6.4 and it is working now without exceptions.
