### ISSUE TITLE
org.gitlab4j.api.models.Deployment->id numeric value out of range of int

### ISSUE THREAD

**Issue by ghmulti** [gitlab4j/gitlab4j-api#828]
Is similar to https://github.com/gitlab4j/gitlab4j-api/issues/743

we are using - org.gitlab4j:gitlab4j-api:4.17.0

Stacktrace:
`
Exception in thread "main" org.gitlab4j.api.GitLabApiException: Numeric value (2215050771) out of range of int (-2147483648 - 2147483647)
 at [Source: (org.glassfish.jersey.client.internal.HttpUrlConnector$2); line: 1, column: 609] (through reference chain: java.util.ArrayList[0]->org.gitlab4j.api.models.Deployment["deployable"]->org.gitlab4j.api.models.Deployable["id"])
	at org.gitlab4j.api.Pager.<init>(Pager.java:97)
	at org.gitlab4j.api.DeploymentsApi.getProjectDeployments(DeploymentsApi.java:79)
`

The solution would be to use Long on org.gitlab4j.api.models.Deployment->id

**Comment by jabby** [comment]
You should use `org.gitlab4j:gitlab4j-api:5.0.0` (already released) or `org.gitlab4j:gitlab4j-api:5.0.1` (release in progress). Main goal of these versions is to replace all IDs from Integer to Long.

**Comment by Whisper40** [comment]
@jabby Hello, regarding the use of Long instead of Int. I changed all my int values to long values, but when i found a project, his projectId is for example "1596", so how to know if i have to search for 1596L or 1596. Maybe i don't understand something
