### ISSUE TITLE
outh2Login with username and password

### ISSUE THREAD

**Issue by fooller** [gitlab4j/gitlab4j-api#854]
`<dependency>
    <groupId>org.gitlab4j</groupId>
    <artifactId>gitlab4j-api</artifactId>
    <version>5.0.1</version>
</dependency>

GitLabApi gitLabApi = GitLabApi.oauth2Login("http://your.gitlab.server.com", "username", "password");

org.gitlab4j.api.GitLabApiException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:326)
        at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:67)
        at org.gitlab4j.api.RepositoryApi.getBranch(RepositoryApi.java:89)`

**Comment by fooller** [comment]
I user this api

GitLabApi gitLabApi = GitLabApi.oauth2Login("http://your.gitlab.server.com/", "username", "password", false);
