### ISSUE TITLE
javax dependencies still in use but not in classpath anymore

### ISSUE THREAD

**Issue by mbogner** [gitlab4j/gitlab4j-api#888]
just found https://github.com/gitlab4j/gitlab4j-api/pull/841 which I guess answers my issue.

When I add the dependency

```kotlin
implementation("org.gitlab4j:gitlab4j-api:5.0.1")
```

to my Spring Boot 3.0.0 application i get the exception:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gitlabApi' defined in class path resource [.../GitlabApiConfig.class]: Failed to instantiate [org.gitlab4j.api.GitLabApi]: Factory method 'gitlabApi' threw exception with message: javax/ws/rs/core/StreamingOutput
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:488) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1324) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1161) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.0.jar:3.0.0]
	at ....AppKt.main(App.kt:22) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-3.0.0.jar:3.0.0]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.gitlab4j.api.GitLabApi]: Factory method 'gitlabApi' threw exception with message: javax/ws/rs/core/StreamingOutput
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.0.2.jar:6.0.2]
	... 24 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/ws/rs/core/StreamingOutput
	at ....config.GitlabApiConfig.gitlabApi(GitlabApiConfig.kt:18) ~[main/:na]
	at ....config.GitlabApiConfig$$SpringCGLIB$$0.CGLIB$gitlabApi$0(<generated>) ~[main/:na]
	at ....config.GitlabApiConfig$$SpringCGLIB$$2.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:257) ~[spring-core-6.0.2.jar:6.0.2]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.0.2.jar:6.0.2]
	at ....config.GitlabApiConfig$$SpringCGLIB$$0.gitlabApi(<generated>) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.2.jar:6.0.2]
	... 25 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.core.StreamingOutput
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 36 common frames omitted
```

So a simple ClassNotFound.

I tried `implementation("javax.ws.rs:javax.ws.rs-api:2.1.1")` but then it also failed with another exception that some types are not compatible. Sure, the jar has a dependency to `jakarta.ws.rs:jakarta.ws.rs-api:3.1.0` but somehow it is still depending/using the old javax namespace.

Example:

```java
package org.gitlab4j.api;
// skip

import javax.ws.rs.NotAuthorizedException;
import javax.ws.rs.core.Form;
import javax.ws.rs.core.MultivaluedMap;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.StreamingOutput;

// skip
public abstract class AbstractApi implements Constants {}
```

These definitely are not in the classpath but there is `jakarta.ws.rs.core.StreamingOutput` for example coming from the new dependency. Looks like the transition isn't finished/working in 5.0.1 yet. Or what am I missing?

**Comment by MrPawelas** [comment]
Hi, does anyone know if this issue is going to be addressed in following weeks? I'm a little bit afraid that this library is dead and just want to make sure if it's worth it to wait.

**Comment by jabby** [comment]
Sorry for delay. I was very busy. This library is not dead. 
To be clear the only work in progress is currently this PR #841but it's not enough. I think we should also ugrade to jdk 17. cf. #817

**Comment by jabby** [comment]
Is an alpha version ok for you in few weeks?

**Comment by mbogner** [comment]
> Hi, does anyone know if this issue is going to be addressed in following weeks? I'm a little bit afraid that this library is dead and just want to make sure if it's worth it to wait.

I tried to use this library in 2 projects now:
 - For the first one I downloaded the source and had to adapt it to get things working as needed because it wasn't up to date with gitlab api. Didn't find the time to polish my fork and create a merge request though and can't even remember what the exact fields were that weren't in sync with the api.
 - Second project I worked around it completely because I'm already using Spring Boot 3 and I didn't want to do the upgrade myself. #841 is from April 2022. First reaction in November. Now its January.

All the effort of the contributors appreciated I wouldn't dare to use this in a customer project right now.

**Comment by mbogner** [comment]
Shouldn't #841 fix this? @jabby

**Comment by walnut-tom** [comment]
Add java9+ and Jakarta EE Support https://github.com/gitlab4j/gitlab4j-api/pull/895

**Comment by jhult** [comment]
@jabby, any news?

It seems like there are multiple PRs that could probably get merged in.

I'm sure there are some in the community that would be willing to help maintain this library (if you so desire).

**Comment by jmini** [comment]
So as discussed in https://github.com/gitlab4j/gitlab4j-api/issues/926 we are now working on a `6.x.x` version of the client on the [`6.x` branch](https://github.com/gitlab4j/gitlab4j-api/tree/6.x).

On this branch we have decided to require **Java 11** as minimal version and we will use Jakarta EE components that are using the `jakarta.*` packages instead of `javax.*` (making this version compatible with Spring Boot 3 application).

**Comment by mbogner** [comment]
This feels exactly like sending a request or bug to gitlab 😂 There all tickets are open for years as well. Another reason to simply avoid this library 😔

**Comment by jmini** [comment]
@mbogner, @jhult and @walnut-tom:

Please check if the release `6.0.0-rc.1` works for you and give feedback, so that we know if we are on the good path for a `6.0.0` release.

I am closing this issue now.

If you need something more, please reopen this issue with exact details about what is missing. Or open a new one.
